# Generated by Django 4.0.6 on 2022-08-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField()),
                ('date', models.DateTimeField()),
                ('date_required', models.DateTimeField()),
                ('contact', models.TextField()),
                ('account', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('terms', models.TextField()),
                ('customer_PO', models.TextField()),
                ('deposit', models.TextField()),
                ('rep', models.TextField()),
                ('csr', models.TextField()),
                ('quantity_1', models.TextField()),
                ('description_1', models.TextField()),
                ('finished_size_1', models.TextField()),
                ('stock_1', models.TextField()),
                ('machine_1', models.TextField()),
                ('run_quantity_1', models.TextField()),
                ('sheet_size_1', models.TextField()),
                ('run_size_1', models.TextField()),
                ('proof_1', models.TextField()),
                ('inks_1', models.TextField()),
                ('instructions_1', models.TextField()),
                ('bindery_1', models.TextField()),
                ('file_1', models.TextField()),
                ('price_comission_1', models.TextField()),
                ('shipping_1', models.TextField()),
                ('quantity_2', models.TextField()),
                ('description_2', models.TextField()),
                ('finished_size_2', models.TextField()),
                ('stock_2', models.TextField()),
                ('machine_2', models.TextField()),
                ('run_quantity_2', models.TextField()),
                ('sheet_size_2', models.TextField()),
                ('run_size_2', models.TextField()),
                ('proof_2', models.TextField()),
                ('inks_2', models.TextField()),
                ('instructions_2', models.TextField()),
                ('bindery_2', models.TextField()),
                ('file_2', models.TextField()),
                ('price_comission_2', models.TextField()),
                ('shipping_2', models.TextField()),
                ('quantity_3', models.TextField()),
                ('description_3', models.TextField()),
                ('finished_size_3', models.TextField()),
                ('stock_3', models.TextField()),
                ('machine_3', models.TextField()),
                ('run_quantity_3', models.TextField()),
                ('sheet_size_3', models.TextField()),
                ('run_size_3', models.TextField()),
                ('proof_3', models.TextField()),
                ('inks_3', models.TextField()),
                ('instructions_3', models.TextField()),
                ('bindery_3', models.TextField()),
                ('file_3', models.TextField()),
                ('price_comission_3', models.TextField()),
                ('shipping_3', models.TextField()),
            ],
        ),
    ]
