# Generated by Django 4.0.6 on 2022-10-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='bindery_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='description_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='file_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='finished_size_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='inks_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='instructions_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='docket',
            name='machine_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='price_comission_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='proof_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='quantity_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='run_quantity_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='run_size_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='sheet_size_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='shipping_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='stock_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
