# Generated by Django 4.0.6 on 2023-02-13 22:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='machine_1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], max_length=200),
        ),
    ]
