# Generated by Django 4.0.6 on 2022-10-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0002_docket_bindery_2_docket_description_2_docket_file_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='bindery_3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='description_3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='file_3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='finished_size_3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='inks_3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='instructions_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='docket',
            name='machine_3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='price_comission_3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='proof_3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='quantity_3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='reception_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='docket',
            name='run_quantity_3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='run_size_3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='sheet_size_3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='shipping_3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docket',
            name='stock_3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
