# Generated by Django 4.0.6 on 2022-08-11 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0002_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ink', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='account',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='bindery_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='bindery_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='bindery_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='customer_PO',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dockets.clients'),
        ),
        migrations.AlterField(
            model_name='docket',
            name='deposit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='description_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='description_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='description_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='file_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='file_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='file_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='finished_size_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='finished_size_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='finished_size_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='inks_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='inks_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='inks_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='machine_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='machine_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='machine_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='price_comission_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='price_comission_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='price_comission_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='proof_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='proof_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='proof_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='quantity_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='quantity_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='quantity_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='run_quantity_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='run_quantity_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='run_quantity_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='run_size_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='run_size_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='run_size_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='sheet_size_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='sheet_size_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='sheet_size_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='shipping_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='shipping_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='shipping_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='stock_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='stock_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='stock_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='terms',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('csr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dockets.csr')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dockets.clients')),
            ],
        ),
        migrations.AlterField(
            model_name='docket',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dockets.contact'),
        ),
        migrations.AlterField(
            model_name='docket',
            name='csr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dockets.csr'),
        ),
        migrations.AlterField(
            model_name='docket',
            name='rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dockets.rep'),
        ),
    ]
