# Generated by Django 4.0.6 on 2022-08-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0003_csr_ink_machine_proof_stock_alter_clients_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clients',
            new_name='Client',
        ),
    ]
