# Generated by Django 4.0.6 on 2022-10-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0003_docket_bindery_3_docket_description_3_docket_file_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='inks_1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='docket',
            name='machine_1',
        ),
        migrations.AddField(
            model_name='docket',
            name='machine_1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docket',
            name='proof_1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docket',
            name='stock_1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
