# Generated by Django 4.0.6 on 2023-02-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0003_alter_docket_machine_1_alter_docket_machine_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='inks1_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='docket',
            name='inks2_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='docket',
            name='inks3_other',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
