# Generated by Django 4.0.6 on 2023-02-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0004_docket_inks1_other_docket_inks2_other_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docket',
            old_name='inks_1',
            new_name='inks1_1',
        ),
        migrations.RenameField(
            model_name='docket',
            old_name='inks1_other',
            new_name='inks1_other1',
        ),
        migrations.RenameField(
            model_name='docket',
            old_name='inks2_other',
            new_name='inks1_other2',
        ),
        migrations.RenameField(
            model_name='docket',
            old_name='inks3_other',
            new_name='inks1_other3',
        ),
        migrations.RenameField(
            model_name='docket',
            old_name='stock_1',
            new_name='stock1_1',
        ),
        migrations.RenameField(
            model_name='docket',
            old_name='stock_2',
            new_name='stock2_1',
        ),
        migrations.RenameField(
            model_name='docket',
            old_name='stock_3',
            new_name='stock3_1',
        ),
        migrations.RemoveField(
            model_name='docket',
            name='inks_2',
        ),
        migrations.RemoveField(
            model_name='docket',
            name='inks_3',
        ),
        migrations.AddField(
            model_name='docket',
            name='inks1_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='docket',
            name='inks1_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='docket',
            name='inks2_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='docket',
            name='inks2_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='docket',
            name='inks2_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='docket',
            name='inks2_other1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='docket',
            name='inks2_other2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='docket',
            name='inks3_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='docket',
            name='inks3_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='docket',
            name='inks3_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='docket',
            name='inks3_other1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='docket',
            name='inks3_other2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='docket',
            name='inks3_other3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='docket',
            name='stock1_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='docket',
            name='stock1_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='docket',
            name='stock2_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='docket',
            name='stock2_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='docket',
            name='stock3_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='docket',
            name='stock3_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
