# Generated by Django 4.0.6 on 2022-10-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0004_alter_docket_inks_1_remove_docket_machine_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='machine_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='docket',
            name='machine_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='docket',
            name='machine_3',
            field=models.CharField(max_length=200),
        ),
    ]
