# Generated by Django 4.0.6 on 2022-08-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0004_rename_clients_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='deposit_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='docket',
            name='quote',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docket',
            name='bindery_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='bindery_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='docket',
            name='date_required',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='docket',
            name='description_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='description_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='file_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='file_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='finished_size_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='finished_size_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='inks_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='inks_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='instructions_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='docket',
            name='instructions_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='docket',
            name='instructions_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='docket',
            name='machine_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='machine_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='price_comission_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='price_comission_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='proof_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='proof_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='quantity_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='quantity_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='run_quantity_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='run_quantity_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='run_size_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='run_size_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='sheet_size_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='sheet_size_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='shipping_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='shipping_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='stock_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='stock_3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
