# Generated by Django 4.0.6 on 2023-02-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0005_rename_inks_1_docket_inks1_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='inks2_other3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
