# Generated by Django 4.0.6 on 2022-11-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0006_docket_flexibility_alter_docket_bindery_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='inks_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docket',
            name='inks_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
