# Generated by Django 4.0.6 on 2023-02-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0006_docket_inks2_other3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docket',
            name='machine_1',
        ),
        migrations.RemoveField(
            model_name='docket',
            name='machine_2',
        ),
        migrations.RemoveField(
            model_name='docket',
            name='machine_3',
        ),
    ]
