# Generated by Django 4.0.6 on 2022-09-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0007_remove_docket_bindery_2_remove_docket_bindery_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docket',
            name='machine_1',
        ),
        migrations.AddField(
            model_name='docket',
            name='machine_1',
            field=models.ManyToManyField(to='Dockets.machine'),
        ),
    ]
