# Generated by Django 4.0.6 on 2023-02-23 23:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0007_remove_docket_machine_1_remove_docket_machine_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='machine_1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='docket',
            name='machine_2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='docket',
            name='machine_3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=100, null=True),
        ),
    ]
