# Generated by Django 4.0.6 on 2022-11-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0007_alter_docket_inks_2_alter_docket_inks_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='proof_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docket',
            name='proof_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
