# Generated by Django 4.0.6 on 2023-02-23 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0008_docket_machine_1_docket_machine_2_docket_machine_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docket',
            old_name='machine_1',
            new_name='machine1',
        ),
        migrations.RenameField(
            model_name='docket',
            old_name='machine_2',
            new_name='machine2',
        ),
        migrations.RenameField(
            model_name='docket',
            old_name='machine_3',
            new_name='machine3',
        ),
    ]
