# Generated by Django 4.0.6 on 2022-11-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0008_alter_docket_proof_2_alter_docket_proof_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='stock_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docket',
            name='stock_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
