# Generated by Django 4.0.6 on 2022-11-28 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0009_alter_docket_stock_2_alter_docket_stock_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docket',
            name='account',
        ),
    ]
