# Generated by Django 4.0.6 on 2023-02-23 23:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0009_rename_machine_1_docket_machine1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='machine1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Xerox 1000', 'Xerox 1000'), ('Xerox Nuvera', 'Xerox Nuvera'), ('Xerox Versant', 'Xerox Versant'), ('Roland', 'Roland'), ('9810', '9810'), ('DI', 'DI'), ('Komori', 'Komori'), ('Outsource', 'Outsource'), ('Design', 'Design'), ('Shippinh', 'Shipping'), ('Mailing', 'Mailing'), ('Postage', 'Postage'), ('PLS', 'PLS'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docket',
            name='machine2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Xerox 1000', 'Xerox 1000'), ('Xerox Nuvera', 'Xerox Nuvera'), ('Xerox Versant', 'Xerox Versant'), ('Roland', 'Roland'), ('9810', '9810'), ('DI', 'DI'), ('Komori', 'Komori'), ('Outsource', 'Outsource'), ('Design', 'Design'), ('Shippinh', 'Shipping'), ('Mailing', 'Mailing'), ('Postage', 'Postage'), ('PLS', 'PLS'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docket',
            name='machine3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Xerox 1000', 'Xerox 1000'), ('Xerox Nuvera', 'Xerox Nuvera'), ('Xerox Versant', 'Xerox Versant'), ('Roland', 'Roland'), ('9810', '9810'), ('DI', 'DI'), ('Komori', 'Komori'), ('Outsource', 'Outsource'), ('Design', 'Design'), ('Shippinh', 'Shipping'), ('Mailing', 'Mailing'), ('Postage', 'Postage'), ('PLS', 'PLS'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
