# Generated by Django 4.0.6 on 2022-10-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0009_remove_docket_email_remove_docket_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docket',
            name='stock_1',
        ),
        migrations.AddField(
            model_name='docket',
            name='stock_1',
            field=models.ManyToManyField(to='Dockets.stock'),
        ),
    ]
