# Generated by Django 4.0.6 on 2022-10-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0011_remove_docket_inks_1_docket_inks_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docket',
            name='inks_1',
        ),
        migrations.AddField(
            model_name='docket',
            name='inks_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dockets.ink'),
        ),
        migrations.RemoveField(
            model_name='docket',
            name='machine_1',
        ),
        migrations.AddField(
            model_name='docket',
            name='machine_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dockets.machine'),
        ),
        migrations.RemoveField(
            model_name='docket',
            name='proof_1',
        ),
        migrations.AddField(
            model_name='docket',
            name='proof_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dockets.proof'),
        ),
        migrations.RemoveField(
            model_name='docket',
            name='stock_1',
        ),
        migrations.AddField(
            model_name='docket',
            name='stock_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dockets.stock'),
        ),
    ]
