# Generated by Django 4.0.6 on 2022-10-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0012_remove_docket_inks_1_docket_inks_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='deposit',
            field=models.CharField(choices=[('1', 'N/A'), ('2', '50%'), ('3', '100%')], max_length=100),
        ),
        migrations.AlterField(
            model_name='docket',
            name='terms',
            field=models.CharField(choices=[('1', 'N/A'), ('2', 'Account'), ('3', 'COD')], max_length=100),
        ),
    ]
