# Generated by Django 4.0.6 on 2022-10-02 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0013_alter_docket_deposit_alter_docket_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='docket',
            name='deposit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dockets.deposit'),
        ),
        migrations.AlterField(
            model_name='docket',
            name='terms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dockets.terms'),
        ),
    ]
