# Generated by Django 4.0.6 on 2022-10-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dockets', '0014_deposit_terms_alter_docket_deposit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docket',
            name='machine_1',
        ),
        migrations.AddField(
            model_name='docket',
            name='machine_1',
            field=models.ManyToManyField(to='Dockets.machine'),
        ),
    ]
