from django import forms
from django.forms import ModelForm
from .models import Docket
from .widgets import DatePickerInput

# Create form for docket creation
class NewDocketForm(ModelForm): #model form for new docket
    class Meta:
        model = Docket #the model it follows
        fields = ('customer_name', 'date', 'date_required', 'contact',  #the fields that are part of the form
                    'account', 'phone', 'email', 'terms', 'customer_PO',
                    'deposit', 'rep', 'csr',
                    'quantity_1', 'description_1', 'finished_size_1', 'stock_1', 'machine_1', 'run_quantity_1', 'sheet_size_1', 'run_size_1', 'proof_1', 'inks_1', 'instructions_1', 'bindery_1', 'file_1', 'price_comission_1', 'shipping_1',
                    'quantity_2', 'description_2', 'finished_size_2', 'stock_2', 'machine_2', 'run_quantity_2', 'sheet_size_2', 'run_size_2', 'proof_2', 'inks_2', 'instructions_2', 'bindery_2', 'file_2', 'price_comission_2', 'shipping_2',
                    'quantity_3', 'description_3', 'finished_size_3', 'stock_3', 'machine_3', 'run_quantity_3', 'sheet_size_3', 'run_size_3', 'proof_3', 'inks_3', 'instructions_3', 'bindery_3', 'file_3', 'price_comission_3', 'shipping_3',
                )
        widgets = { #allows utilization of bootstrap form controls and styling
            'customer_name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Client Name'}),
            'date': DatePickerInput(attrs={'class': 'form-control'}), #using custom datepicker widget
            'date_required': DatePickerInput(attrs={'class': 'form-control'}),
            'contact': forms.TextInput(attrs={'class':'form-control'}),
            'account': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Account'}),
            'phone': forms.TextInput(attrs={'class':'form-control', 'placeholder':'(xxx)-xxx-xxxx'}),
            'email': forms.TextInput(attrs={'class':'form-control', 'placeholder':'user@company.com'}),
            'terms': forms.TextInput(attrs={'class':'form-control'}),
            'customer_PO': forms.TextInput(attrs={'class':'form-control'}),
            'deposit': forms.TextInput(attrs={'class':'form-control'}),
            'rep': forms.TextInput(attrs={'class':'form-control'}),
            'csr': forms.TextInput(attrs={'class':'form-control'}),
            'quantity_1': forms.TextInput(attrs={'class':'form-control'}),
            'description_1': forms.TextInput(attrs={'class':'form-control'}),
            'finished_size_1': forms.TextInput(attrs={'class':'form-control'}),
            'stock_1': forms.TextInput(attrs={'class':'form-control'}),
            'machine_1': forms.TextInput(attrs={'class':'form-control'}),
            'run_quantity_1': forms.TextInput(attrs={'class':'form-control'}),
            'sheet_size_1': forms.TextInput(attrs={'class':'form-control'}),
            'run_size_1': forms.TextInput(attrs={'class':'form-control'}),
            'proof_1': forms.TextInput(attrs={'class':'form-control'}),
            'inks_1': forms.TextInput(attrs={'class':'form-control'}),
            'instructions_1': forms.TextInput(attrs={'class':'form-control'}),
            'bindery_1': forms.TextInput(attrs={'class':'form-control'}),
            'file_1': forms.TextInput(attrs={'class':'form-control'}),
            'price_comission_1': forms.TextInput(attrs={'class':'form-control'}),
            'shipping_1': forms.TextInput(attrs={'class':'form-control'}),
            'quantity_2': forms.TextInput(attrs={'class':'form-control'}),
            'description_2': forms.TextInput(attrs={'class':'form-control'}),
            'finished_size_2': forms.TextInput(attrs={'class':'form-control'}),
            'stock_2': forms.TextInput(attrs={'class':'form-control'}),
            'machine_2': forms.TextInput(attrs={'class':'form-control'}),
            'run_quantity_2': forms.TextInput(attrs={'class':'form-control'}),
            'sheet_size_2': forms.TextInput(attrs={'class':'form-control'}),
            'run_size_2': forms.TextInput(attrs={'class':'form-control'}),
            'proof_2': forms.TextInput(attrs={'class':'form-control'}),
            'inks_2': forms.TextInput(attrs={'class':'form-control'}),
            'instructions_2': forms.TextInput(attrs={'class':'form-control'}),
            'bindery_2': forms.TextInput(attrs={'class':'form-control'}),
            'file_2': forms.TextInput(attrs={'class':'form-control'}),
            'price_comission_2': forms.TextInput(attrs={'class':'form-control'}),
            'shipping_2': forms.TextInput(attrs={'class':'form-control'}),
            'quantity_3': forms.TextInput(attrs={'class':'form-control'}),
            'description_3': forms.TextInput(attrs={'class':'form-control'}),
            'finished_size_3': forms.TextInput(attrs={'class':'form-control'}),
            'stock_3': forms.TextInput(attrs={'class':'form-control'}),
            'machine_3': forms.TextInput(attrs={'class':'form-control'}),
            'run_quantity_3': forms.TextInput(attrs={'class':'form-control'}),
            'sheet_size_3': forms.TextInput(attrs={'class':'form-control'}),
            'run_size_3': forms.TextInput(attrs={'class':'form-control'}),
            'proof_3': forms.TextInput(attrs={'class':'form-control'}),
            'inks_3': forms.TextInput(attrs={'class':'form-control'}),
            'instructions_3': forms.TextInput(attrs={'class':'form-control'}),
            'bindery_3': forms.TextInput(attrs={'class':'form-control'}),
            'file_3': forms.TextInput(attrs={'class':'form-control'}),
            'price_comission_3': forms.TextInput(attrs={'class':'form-control'}),
            'shipping_3': forms.TextInput(attrs={'class':'form-control'}),
        }
