from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Docket(models.Model): #contains all the data for a docket to be stored in the database
    customer_name = models.CharField(max_length = 100)
    date = models.DateTimeField()
    date_required = models.DateTimeField()
    contact = models.CharField(max_length = 100)
    account = models.CharField(max_length = 100)
    phone = models.CharField(max_length = 100)
    email = models.EmailField(max_length = 100)
    terms = models.CharField(max_length = 100)
    customer_PO = models.CharField(max_length = 100)
    deposit = models.CharField(max_length = 100)
    rep = models.CharField(max_length = 100)
    csr = models.CharField(max_length = 100)
    quantity_1 = models.CharField(max_length = 100)
    description_1 = models.CharField(max_length = 100)
    finished_size_1 = models.CharField(max_length = 100)
    stock_1 = models.CharField(max_length = 100)
    machine_1 = models.CharField(max_length = 100)
    run_quantity_1 = models.CharField(max_length = 100)
    sheet_size_1 = models.CharField(max_length = 100)
    run_size_1 = models.CharField(max_length = 100)
    proof_1 = models.CharField(max_length = 100)
    inks_1 = models.CharField(max_length = 100)
    instructions_1 = models.TextField()
    bindery_1 = models.CharField(max_length = 100)
    file_1 = models.CharField(max_length = 100)
    price_comission_1 = models.CharField(max_length = 100)
    shipping_1 = models.CharField(max_length = 100)
    quantity_2 = models.CharField(max_length = 100)
    description_2 = models.CharField(max_length = 100)
    finished_size_2 = models.CharField(max_length = 100)
    stock_2 = models.CharField(max_length = 100)
    machine_2 = models.CharField(max_length = 100)
    run_quantity_2 = models.CharField(max_length = 100)
    sheet_size_2 = models.CharField(max_length = 100)
    run_size_2 = models.CharField(max_length = 100)
    proof_2 = models.CharField(max_length = 100)
    inks_2 = models.CharField(max_length = 100)
    instructions_2 = models.TextField()
    bindery_2 = models.CharField(max_length = 100)
    file_2 = models.CharField(max_length = 100)
    price_comission_2 = models.CharField(max_length = 100)
    shipping_2 = models.CharField(max_length = 100)
    quantity_3 = models.CharField(max_length = 100)
    description_3 = models.CharField(max_length = 100)
    finished_size_3 = models.CharField(max_length = 100)
    stock_3 = models.CharField(max_length = 100)
    machine_3 = models.CharField(max_length = 100)
    run_quantity_3 = models.CharField(max_length = 100)
    sheet_size_3 = models.CharField(max_length = 100)
    run_size_3 = models.CharField(max_length = 100)
    proof_3 = models.CharField(max_length = 100)
    inks_3 = models.CharField(max_length = 100)
    instructions_3 = models.TextField()
    bindery_3 = models.CharField(max_length = 100)
    file_3 = models.CharField(max_length = 100)
    price_comission_3 = models.CharField(max_length = 100)
    shipping_3 = models.CharField(max_length = 100)


class clients(models.Model): #database table to hold all client names
    name = models.CharField(max_length = 100)
